image:
  file: .gitpod.Dockerfile
tasks:
  - init: make build && abtnode init -f --mode debug
    command: abtnode start && blocklet dev
ports:
  - port: 8080
    onOpen: ignore
  - port: 4430
    onOpen: ignore
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
